apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  namespace: devops-tools
  labels:
    app: nodeapp
spec:
  containers:
  - name: nodeapp
    image: 0352730247/node-app:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080

# apiVersion: v1
# kind: Pod
# metadata:
#   name: nodeapp
#   namespace: devops-tools
#   labels:
#     app: nodeapp
# spec:
#   containers:
#     - name: nodeapp
#       image: kammana/nodeapp:v1
#       ports:
#         - containerPort: 8080